### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by md-innovative** [Innovative-Foundation/universe-cli#1]
- [ ] npm
  - [x] check
  - [x] init
  - [x] install package
  - [ ] packages explorer
  - [ ] run scripts
- [ ] git
  - [x] init repository
  - [ ] checkout
  - [ ] reset --hard
  - [ ] stash support
- [ ] Project
  - [ ] up-to-date
  - [ ] clean/modified
  - [ ] init  
  - [ ] angular
    - [ ] schematics  
  - [ ] vite
    - [ ] init vanilla js
    - [ ] init reactjs
    - [ ] init vue
  - [ ] node cli
    - [ ] cli.js as main end point
    - [ ] shebang #!/usr/bin/env node
   - [ ] node
     - [ ] create directory
     - [ ] check/init package.json
     - [ ] javascript
     - [ ] typescript
       - [ ] tsnd dev server
       - [ ] init tsconfig.json
       - [ ] init tslint.json
